-- OKX x Dubai Cares — Full 118-creator seed (Alaa's list only, no Our Pick)
-- Run in Supabase SQL Editor AFTER deleting old data:
-- DELETE FROM okx_outreach;

INSERT INTO okx_outreach (name, handle, ig_url, wave, okx_status, nationality, category, followers, notes) VALUES
  ('Lojain Omran','@lojain_omran','https://www.instagram.com/lojain_omran/','P1','OKX Approved','Saudi Arabian','','11.7M',''),
  ('The National News','@thenationalnews.com','https://www.instagram.com/thenationalnews.com/','P1','OKX Approved','UAE','','','UAE-based English-language newspaper covering local and global news.'),
  ('Megan Al Marzooqi','@realmumsuae','https://www.instagram.com/realmumsuae/','P1','OKX Approved','Emirati','','','Founder of Real Mums UAE, a platform for mothers to share parenting advice and lifestyle tips.'),
  ('Anas Bukhash','@ANASBOUKHASH','https://www.instagram.com/ANASBOUKHASH/','P1','OKX Approved','Emirati','','','Entrepreneur and host of #ABtalks, a series of candid interviews with influential personalities.'),
  ('Mayssoun Azzam','@mayssounazzam','https://www.instagram.com/mayssounazzam/','P1','OKX Approved','Palestinian','','','News anchor and journalist known for her work on Al Arabiya News Channel.'),
  ('Maitha Al Hashemi','@maithav','https://www.instagram.com/maithav/','P1','OKX Approved','Emirati','','','UAE-based lifestyle influencer promoting Emirati culture.'),
  ('Haya Kaabar','@thedubailist','https://www.instagram.com/thedubailist/','P1','OKX Approved','UAE','','','Personal blogger showcasing dining and lifestyle spots.'),
  ('Mohamed S Thani','@mthani1','https://www.instagram.com/mthani1/','P1','OKX Approved','UAE','','','Influencer sharing personal life and experiences.'),
  ('UAE Blogger (Yousef Alkaabi)','@yousef_alkaabi','https://www.instagram.com/yousef_alkaabi/','P1','OKX Approved','UAE','','','Arabic content creator.'),
  ('Live With Aziz','@livewithaziz','https://www.instagram.com/livewithaziz/','P1','OKX Approved','UAE','','','Financial auditor and food/lifestyle creator.'),
  ('Moayad AlSawaf (More Cravings)','@moayad.alsawaf','https://www.instagram.com/moayad.alsawaf/','P1','OKX Approved','UAE','','','Fine dining reviewer.'),
  ('Taim AlFalasi','@taimalfalasi','https://www.instagram.com/taimalfalasi/','P1','OKX Approved','UAE','','','Travel, food, lifestyle.'),
  ('Anthony Rahayel','@nogarlicnoonions','https://www.instagram.com/nogarlicnoonions/','P1','OKX Approved','Lebanese','','','Culinary influencer.'),
  ('Aziz Almarzouqi','@fex','https://www.instagram.com/fex/?hl=en','P1','OKX Approved','Emirati','','','Social media personality (Fex).'),
  ('Miled Rahal','@miledrahal','https://www.instagram.com/miledrahal/','P1','OKX Approved','Lebanese','','','Lifestyle and fashion influencer.'),
  ('Ali & Walaa','@aliandwalaa','https://www.instagram.com/aliandwalaa/','P1','OKX Approved','Lebanese','','','Couple account sharing family and lifestyle.'),
  ('Mahira Abdelaziz','@mahiraabdelaziz','https://www.instagram.com/mahiraabdelaziz/?hl=en','P1','OKX Approved','Emirati','','','Media personality.'),
  ('Mustafa Agha','@musta_agha','https://www.instagram.com/musta_agha/','P2','OKX Listed','Syrian-British','','4.5M','Renowned sports journalist and MBC presenter known for his coverage of regional and international sports.'),
  ('Al Oula Radio','@aloulafm','https://www.instagram.com/aloulafm/','P2','OKX Listed','Emirati','','34.2K','UAE-based radio station offering a variety of programming including music, talk shows, and cultural content.'),
  ('Natuzzi Italia Dubai','@natuzzi.uae','https://www.instagram.com/natuzzi.uae/','P2','OKX Listed','Italian','','24.7K','Italian furniture brand showcasing high-quality, stylish home furnishings in Dubai.'),
  ('Zozo Kahramana','@zozokahramana','https://www.instagram.com/zozokahramana/','P2','OKX Listed','','','','Social media personality known for humorous content and lifestyle posts.'),
  ('GRIT+TONIC.com','@gritandtonic','https://www.instagram.com/gritandtonic/','P2','OKX Listed','','','','Online store providing fitness and wellness products in the UAE.'),
  ('Nawar H','@nawar.h6','https://www.instagram.com/nawar.h6/','P2','OKX Listed','','','','Content creator known for lifestyle and fashion posts.'),
  ('TFG 7 Emirates Cycle Challenge','@tfg7ecc','https://www.instagram.com/tfg7ecc/','P2','OKX Listed','Emirati','','','UAE cycling initiative promoting fitness and community engagement.'),
  ('OutQore','@outqore','https://www.instagram.com/outqore/','P2','OKX Listed','Not specified','','','Community page promoting activities, events, and lifestyle content.'),
  ('UAE Barq','@uae_barq','https://www.instagram.com/uae_barq/','P2','OKX Listed','Emirati','','','News outlet sharing local and international news updates in Arabic.'),
  ('Rooted Regimen','@rootedregimen','https://www.instagram.com/rootedregimen/','P2','OKX Listed','Not specified','','','Health and wellness brand focusing on natural products and lifestyle tips.'),
  ('Ali F. Mostafa','@alimostafa','https://www.instagram.com/alimostafa/','P2','OKX Listed','Emirati','','','Emirati filmmaker known for his work in the Arab cinema industry.'),
  ('Dima Al Sharif','@dimasharifonline','https://www.instagram.com/dimasharifonline/','P2','OKX Listed','Palestinian','','','Culinary expert and author sharing recipes and insights into Middle Eastern cuisine.'),
  ('Nouran M. Fawzy','@nmfeats','https://www.instagram.com/nmfeats/','P2','OKX Listed','Not specified','','','Influencer and content creator sharing lifestyle and motivational content.'),
  ('Firas Nour','@firas.nour','https://www.instagram.com/firas.nour/','P2','OKX Listed','Not specified','','','Lifestyle influencer known for travel and adventure content.'),
  ('Zahra Abdalla','@cookingwithzahra','https://www.instagram.com/cookingwithzahra/','P2','OKX Listed','Not specified','','','Food blogger sharing Middle Eastern recipes and cooking tips.'),
  ('Lisa Helly Obrien','@MyLittleLovesBlog','https://www.instagram.com/MyLittleLovesBlog/','P2','OKX Listed','Not specified','','','Family and lifestyle blogger sharing parenting tips and family adventures.'),
  ('Mohamed Zidan','@Zidan_DXB','https://www.instagram.com/Zidan_DXB/','P2','OKX Listed','Egyptian','','','Egyptian footballer and former professional player, now active in lifestyle and sports content.'),
  ('DU','@Du','https://www.instagram.com/Du/','P2','OKX Listed','Emirati','','','UAE-based telecommunications company providing mobile and internet services.'),
  ('Lovin Dubai','@lovindubai','https://www.instagram.com/lovindubai/','P2','OKX Listed','Not specified','','','Lifestyle news outlet covering events, activities, and happenings in Dubai.'),
  ('Farah Abdulhamed','@farahabdulhamed','https://www.instagram.com/farahabdulhamed/','P2','OKX Listed','Jordanian','','','Beauty and lifestyle influencer known for her makeup tutorials and style tips.'),
  ('Etisalat e&','@etisalat','https://www.instagram.com/etisalat/','P2','OKX Listed','Emirati','','','Leading telecommunications provider in the UAE, offering a range of mobile and internet services.'),
  ('Haifa Beseisso','@flywithhaifa','https://www.instagram.com/flywithhaifa/','P2','OKX Listed','Palestinian','','','Also known as Fly With Haifa; travel influencer promoting cultural exchange.'),
  ('Rama Murad','@raamamurad','https://www.instagram.com/raamamurad/','P2','OKX Listed','','','','Lifestyle and fashion influencer.'),
  ('Zahra Abdalla (Zahra''s Kitchen)','@cookingwithzahra','https://www.instagram.com/cookingwithzahra/','P2','OKX Listed','Iran and Sudan','','','Food influencer and cookbook author; founder of Zahra''s Kitchen.'),
  ('Alex Augusti (JustFoodDXB)','@justfooddxb','https://www.instagram.com/justfooddxb/','P2','OKX Listed','UAE','','','Dubai-based food influencer sharing casual dining recommendations.'),
  ('Lavina Israni','@lavinaisranicom','https://www.instagram.com/lavinaisranicom/','P2','OKX Listed','UAE','','','Content creator and food writer.'),
  ('Karen Mcclean (Secret Squirrel Food)','@secretsquirrelfood','https://www.instagram.com/secretsquirrelfood/','P2','OKX Listed','Australia','','','Award-winning food blogger; founder of Secret Squirrel Food.'),
  ('Mona Essawi','@cookingis.art','https://www.instagram.com/cookingis.art/','P2','OKX Listed','UAE and Egypt','','','Healthy lifestyle influencer focused on nutritious meals.'),
  ('Nahla Ibrahim','@nahlaaibrahiim','https://www.instagram.com/nahlaaibrahiim/','P2','OKX Listed','Saudi Arabia and Egypt','','','Lifestyle influencer sharing restaurants, hotels, beauty, and fashion.'),
  ('Virdah Javed Khan','@mom_in_dubai','https://www.instagram.com/mom_in_dubai/','P2','OKX Listed','Pakistan','','','Dubai-based influencer specializing in food, fashion, and lifestyle.'),
  ('Aaisha','@dubai_blogger__','https://www.instagram.com/dubai_blogger__/','P2','OKX Listed','India','','','Food, fashion, and lifestyle blogger.'),
  ('Rafeez Ahmed','@tableeforone','https://www.instagram.com/tableeforone/','P2','OKX Listed','India','','','UAE-based food blogger.'),
  ('Safia Mansoor','@cuptaleswithsafia','https://www.instagram.com/cuptaleswithsafia/','P2','OKX Listed','India','','','Food and travel creator.'),
  ('Ayshafarhana Tharammal','@ayeshas_kitche_n','https://www.instagram.com/ayeshas_kitche_n/','P3','OKX Listed','India','','','Social media influencer and YouTuber.'),
  ('Olena','@health_and_beauty_uae','https://www.instagram.com/health_and_beauty_uae/','P3','OKX Listed','Not specified','','','UAE influencer showcasing hidden gem restaurants.'),
  ('Sultan Kayed','@sultan.eats','https://www.instagram.com/sultan.eats/','P3','OKX Listed','UAE','','','Chef and owner of Goat; food blogger.'),
  ('Pooja Varyani','@foodishvibes','https://www.instagram.com/foodishvibes/','P3','OKX Listed','India','','','Vegetarian food vlogger.'),
  ('Anushree Bagzai','@anushreebagzai','https://www.instagram.com/anushreebagzai/','P3','OKX Listed','India','','','Dubai-based blogger focused on travel, food, lifestyle.'),
  ('Arpita Soni','@foodloreuae','https://www.instagram.com/foodloreuae/','P3','OKX Listed','India','','','Abu Dhabi-based content creator and food blogger.'),
  ('Jedax Foodtrip','@jedax.foodtrip','https://www.instagram.com/jedax.foodtrip/','P3','OKX Listed','Philippines','','','Top Filipino influencers in UAE; food and travel.'),
  ('Syed Muhammad Shabi ul Hasnain','@shaybishah','https://www.instagram.com/shaybishah/','P3','OKX Listed','Pakistan','','','Food connoisseur and founder of Eat Sleep Repeat.'),
  ('Aemen Aisha','@adventuresofaemen','https://www.instagram.com/adventuresofaemen/','P3','OKX Listed','Pakistan','','','Lifestyle, food, activities influencer; founder of Create With Aemen.'),
  ('Danah Alshayji','@danaindxb','https://www.instagram.com/danaindxb/','P3','OKX Listed','tUAE','','','Kuwaiti mom of three living in Dubai; lifestyle content.'),
  ('Hupert Sepidnam (Mr. Taster)','@mr.taster','https://www.instagram.com/mr.taster/','P3','OKX Listed','UK','','','International food blogger based in Dubai.'),
  ('Abu Julia أبو جوليا','@abu_juliaa','https://www.instagram.com/abu_juliaa/','P3','OKX Listed','UAE & UK','','','Food influencer.'),
  ('S7S 👌🏼 سحس','@hussain.sallam','https://www.instagram.com/hussain.sallam/','P3','OKX Listed','KSA','','','Food influencer.'),
  ('Dubai Diarys - Ayesha Runeza sheikh','@dubaidiarys','https://www.instagram.com/dubaidiarys/','P3','OKX Listed','India','','','Digital content creator.'),
  ('Food Voyager','@food__voyager','https://www.instagram.com/food__voyager/','P3','OKX Listed','India','','','Based in Dubai and Bangalore, showcasing food and hotels.'),
  ('Chef IZU','@chefizu','https://www.instagram.com/chefizu/','P3','OKX Listed','French','','','Restaurateur and culinary artist.'),
  ('Yasmine Idriss Tannir','@petites_choses','https://www.instagram.com/petites_choses/','P3','OKX Listed','Lebanon','','','Digital creator.'),
  ('Soul AbouZahr','@soulselections','https://www.instagram.com/soulselections/','P3','OKX Listed','Lebanon','','','Food writer/speaker/TV host.'),
  ('Zahra Lyla Khalil','@zahralyla','https://www.instagram.com/zahralyla/','P3','OKX Listed','Iranian/UAE','','','Creative Director.'),
  ('Latifa Alshamsi','@latifalshamsi','https://www.instagram.com/latifalshamsi/','P3','OKX Listed','UAE','','','Emirati Fashion, Food & Travel Blogger.'),
  ('Feras Abo Shaar','@ferasaboshaar','https://www.instagram.com/ferasaboshaar/','P3','OKX Listed','Syrian','','','Food blogger.'),
  ('Ellie Z Amin','@dubaifoodlovers','https://www.instagram.com/dubaifoodlovers/','P3','OKX Listed','Iranian','','','Food and lifestyle.'),
  ('Areej Nashashibi','@areejnashashibi','https://www.instagram.com/areejnashashibi/','P3','OKX Listed','Syrian','','','Entrepreneur and content creator.'),
  ('Khaled B2k','@khaled_b2k','https://www.instagram.com/khaled_b2k/','P3','OKX Listed','UAE','','','Blogger.'),
  ('Coral Stevens','@DXB_Hun','https://www.instagram.com/DXB_Hun/','P3','OKX Listed','British','','','Digital creator.'),
  ('Firas Kazma','@firaskazma','https://www.instagram.com/firaskazma/','P3','OKX Listed','Lebanese','','','Digital entrepreneur and motivational speaker.'),
  ('Wissam Breidy','@wissambreidy','https://www.instagram.com/wissambreidy/','P3','OKX Listed','Lebanese','','','TV host and media personality.'),
  ('Rym Saidi','@rymsaidi','https://www.instagram.com/rymsaidi/','P3','OKX Listed','Tunisian-Lebanese','','','Model and TV personality.'),
  ('Mouhanad Al Wadiya','@mohanadalwadiya','https://www.instagram.com/mohanadalwadiya/?hl=en','P3','OKX Listed','Iraqi','','','Real estate expert.'),
  ('Joelle Mardinian','@joellemardinian','https://www.instagram.com/joellemardinian/','P3','OKX Listed','Lebanese','','','Beauty expert and entrepreneur.'),
  ('Munther Almuzaki','@m_almuzaki','https://www.instagram.com/m_almuzaki/','P3','OKX Listed','Emirati','','','Lifestyle influencer.'),
  ('Jessica Kahawati','@jessicakahawaty','https://www.instagram.com/jessicakahawaty/','P3','OKX Listed','Lebanese-Australian','','','Model, lawyer, humanitarian.'),
  ('Karen Wazen','@karenwazen','https://www.instagram.com/karenwazen/','P3','OKX Listed','Labanese-British','','','Fashion influencer.'),
  ('Kris Fade','@krisfade','https://www.instagram.com/krisfade/','P3','OKX Listed','Lebanese-Australian','','','Radio presenter and entrepreneur.'),
  ('Zeina Khoury','@thezeinakhoury','https://www.instagram.com/thezeinakhoury/','P3','OKX Listed','Lebanese','','','CEO of High Mark Real Estate.'),
  ('Mona Kattan','@monakattan','https://www.instagram.com/monakattan/','P3','OKX Listed','Iraqi-American','','','Co-founder of Huda Beauty.'),
  ('Huda Kattan','@hudabeauty','https://www.instagram.com/hudabeauty/','P3','OKX Listed','Iraqi-American','','','Founder of Huda Beauty.'),
  ('Anas Marwah','@anasmarwah','https://www.instagram.com/anasmarwah/','P3','OKX Listed','Syrian-Canadian','','','Family content creator.'),
  ('Raquel Zaatar','@raquelthym','https://www.instagram.com/raquelthym/','P3','OKX Listed','Lebanese','','','Lifestyle influencer.'),
  ('Tamara Farra','@tamara_farra','https://www.instagram.com/tamara_farra/','P3','OKX Listed','Lebanese','','','Fashion and lifestyle influencer.'),
  ('Sophia bi chahine','@sophiabichahine','https://www.instagram.com/sophiabichahine/','P3','OKX Listed','Lebanese','','','Lifestyle influencer.'),
  ('Salwa Azzam','@salwaazzam','https://www.instagram.com/salwaazzam/','P3','OKX Listed','Lebanese','','','Lifestyle influencer.'),
  ('Sara Zeaiter','@sarazeaiter','https://www.instagram.com/sarazeaiter/','P3','OKX Listed','Lebanese','','','Lifestyle influencer.'),
  ('Sara Karrit','@sarakarrit','https://www.instagram.com/sarakarrit/','P3','OKX Listed','Lebanese','','','Beauty and lifestyle influencer.'),
  ('Katia Samra','@katiasamra','https://www.instagram.com/katiasamra/','P3','OKX Listed','Syrian','','','Entrepreneur and influencer.'),
  ('Maya Ahmad','@mayaahmad','https://www.instagram.com/mayaahmad/','P3','OKX Listed','Lebanese','','','Beauty influencer and makeup artist.'),
  ('Tracy Harmoush','@tracyharmoush','https://www.instagram.com/tracyharmoush/','P3','OKX Listed','Lebanese','','','Fitness influencer.'),
  ('Rony Mhanna','@ronymhanna','https://www.instagram.com/ronymhanna/','P3','OKX Listed','Lebanese','','','Lifestyle content creator.'),
  ('Remi E Salloum','@remiesalloum','https://www.instagram.com/remiesalloum/','P3','OKX Listed','Lebanese','','','Lifestyle content creator.'),
  ('Sarah Abdallah','@dubaiprettyladies','https://www.instagram.com/dubaiprettyladies/','P3','OKX Listed','Lebanese','','','Founder of Dubai Pretty Ladies.'),
  ('Lynn Laz','@lynnlaz','https://www.instagram.com/lynnlaz/','P3','OKX Listed','Lebanese','','','Fashion and lifestyle influencer.'),
  ('Hiba Hassan','@dr.hibahassan','https://www.instagram.com/dr.hibahassan/','P3','OKX Listed','Lebanese','','','Medical influencer.'),
  ('Elena El Sabbagh','@elenaelsabbagh','https://www.instagram.com/elenaelsabbagh/?hl=en','P3','OKX Listed','Lebanese-Russian','','','Lifestyle content blending heritage.'),
  ('Paola Boulos El Sitt','@mllepaola','https://www.instagram.com/mllepaola/','P3','OKX Listed','Lebanese','','','Fashion, beauty, lifestyle.'),
  ('Ziad AboShaar','@ziadaboshaar','https://www.instagram.com/ziadaboshaar/?hl=en','P3','OKX Listed','Syrian','','','Content creator.'),
  ('Mohamed Karaki','@mhamad_karaki','https://www.instagram.com/mhamad_karaki/?hl=en','P3','OKX Listed','Lebanese','','','Lifestyle influencer.'),
  ('Juwayria Ghazali','@j.ghaz','https://www.instagram.com/j.ghaz/?hl=en','P3','OKX Listed','English','','','Lifestyle influencer.'),
  ('Aishah Hamdi Mohamed','@aisha.cryptosy','https://www.instagram.com/aisha.cryptosy/','P3','OKX Listed','Egyptian','','','Lifestyle and cultural content.'),
  ('Dalia Monzer Zaouil','@daliazawil_dxb','https://www.instagram.com/daliazawil_dxb/','P3','OKX Listed','Lebanese','','','Lifestyle and fashion influencer.'),
  ('myfashdiary (Tala Samman)','@myfashdiary','https://www.instagram.com/myfashdiary/','P3','OKX Listed','Syrian-American','','','Founder of MyFashDiary.'),
  ('Rima Zahran','@rimazahran','https://www.instagram.com/rimazahran/','P3','OKX Listed','Emirati-Palestinian','','','Fashion designer.'),
  ('Nada Alshaibani','@nada.alshaibani1','https://www.instagram.com/nada.alshaibani1/','P3','OKX Listed','Bahraini','','','Beauty and lifestyle influencer.'),
  ('Mariam Hussein','@mariamhusseinofficial','https://www.instagram.com/mariamhusseinofficial/','P3','OKX Listed','','','','Social media personality and actress.'),
  ('Um Saeed','@um_saeed176_','https://www.instagram.com/um_saeed176_/','P3','OKX Listed','Emirati','','','Traditional Emirati content.'),
  ('Cyrelle Balian','@cyrelle.balian','https://www.instagram.com/cyrelle.balian/','P3','OKX Listed','Lebanon','','','Beauty and wellness content.'),
  ('Pooja Gosalia','@thepoojasblog','https://www.instagram.com/thepoojasblog/','P3','OKX Listed','India','','29.9K','UAE-based content creator specializing in food, fashion, and lifestyle.'),
  ('Fathima (HalaFathi)','@_halafathi','https://www.instagram.com/_halafathi/','P3','OKX Listed','UAE','','15.2K','Shares reviews of restaurants and explores Dubai’s food scene.'),
  ('Sandra Boghos Letayf','@sandyskitchen','https://www.instagram.com/sandyskitchen/','P3','OKX Listed','Lebanon','','140K','Recipe developer.');