-- OKX Campaign Tracker — Pre-seed all 73 creators
-- Run AFTER setup.sql in Supabase SQL Editor

INSERT INTO okx_outreach (name, handle, ig_url, wave, okx_status, nationality, category, followers) VALUES

-- === WAVE P1: PRIORITY 15 ===
('Lojain Omran','@lojain_omran','https://www.instagram.com/lojain_omran/','P1','OKX Approved','Saudi Arabian','Lifestyle / Mega',  '11.7M'),
('Mustafa Agha','@musta_agha','https://www.instagram.com/musta_agha/','P1','OKX Listed','Syrian-British','Journalism / MBC','4.5M'),
('Khalid Al Ameri','@khalidalameri','https://www.instagram.com/khalidalameri/','P1','Our Pick','Emirati','Lifestyle / Storytelling','3M'),
('Anas Bukhash','@ANASBOUKHASH','https://www.instagram.com/ANASBOUKHASH/','P1','OKX Approved','Emirati','Entrepreneur / Talk Show','3M'),
('Sham Idrees','@shamidrees','https://www.instagram.com/shamidrees/','P1','Our Pick','UAE','Family / Lifestyle','2M+'),
('Mohammad Galadari','@thisisgaladari','https://www.instagram.com/thisisgaladari/','P1','Our Pick','UAE','Crypto / Finance','888K'),
('Mohammed Alsaadi','@xaex','https://www.instagram.com/xaex/','P1','Our Pick','UAE','Crypto / Arab KOL','784K'),
('Nourhan Elgouhary','@nourhanelgouhary','https://www.instagram.com/nourhanelgouhary/','P1','Our Pick','Egyptian-UAE','Lifestyle / Modest','710K'),
('Amrita Sethi','@art.by.amrita','https://www.instagram.com/art.by.amrita/','P1','Our Pick','UAE','NFT / Art / Creative','675K'),
('Haifa Beseisso','@flywithhaifa','https://www.instagram.com/flywithhaifa/','P1','OKX Listed','Palestinian','Travel / Culture','500K+'),
('Mahira Abdelaziz','@mahiraabdelaziz','https://www.instagram.com/mahiraabdelaziz/','P1','OKX Approved','Emirati','Media Personality','—'),
('Mayssoun Azzam','@mayssounazzam','https://www.instagram.com/mayssounazzam/','P1','OKX Approved','Palestinian','Journalism / Al Arabiya','—'),
('Tapas Mohanta','@legendoftrading','https://www.instagram.com/legendoftrading/','P1','Our Pick','India-UAE','Crypto / Expat','238K'),
('Matthias Mende','@mende','https://www.instagram.com/mende/','P1','Our Pick','European-UAE','Startup / Crypto','203K'),
('Maitha Al Hashemi','@maithav','https://www.instagram.com/maithav/','P1','OKX Approved','Emirati','Lifestyle / Culture','—'),

-- === WAVE P2: MID-RANGE ===
('Mohamed S Thani','@mthani1','https://www.instagram.com/mthani1/','P2','OKX Approved','UAE','Lifestyle','—'),
('Haya Kaabar','@thedubailist','https://www.instagram.com/thedubailist/','P2','OKX Approved','UAE','Dining / Lifestyle','—'),
('Yousef Alkaabi','@yousef_alkaabi','https://www.instagram.com/yousef_alkaabi/','P2','OKX Approved','UAE','Arabic Content','—'),
('Live With Aziz','@livewithaziz','https://www.instagram.com/livewithaziz/','P2','OKX Approved','UAE','Finance / Lifestyle','—'),
('Anthony Rahayel','@nogarlicnoonions','https://www.instagram.com/nogarlicnoonions/','P2','OKX Approved','Lebanese','Culinary / Food','—'),
('Aziz Almarzouqi (Fex)','@fex','https://www.instagram.com/fex/','P2','OKX Approved','Emirati','Personality / Youth','—'),
('Miled Rahal','@miledrahal','https://www.instagram.com/miledrahal/','P2','OKX Approved','Lebanese','Lifestyle / Fashion','—'),
('Ali & Walaa','@aliandwalaa','https://www.instagram.com/aliandwalaa/','P2','OKX Approved','Lebanese','Couple / Family','—'),
('Moayad AlSawaf (More Cravings)','@moayad.alsawaf','https://www.instagram.com/moayad.alsawaf/','P2','OKX Approved','UAE','Fine Dining','—'),
('Taim AlFalasi','@taimalfalasi','https://www.instagram.com/taimalfalasi/','P2','OKX Approved','UAE','Travel / Lifestyle','—'),
('Megan Al Marzooqi (Real Mums UAE)','@realmumsuae','https://www.instagram.com/realmumsuae/','P2','OKX Approved','Emirati','Parenting / Lifestyle','—'),
('Mohamed Zidan','@Zidan_DXB','https://www.instagram.com/Zidan_DXB/','P2','OKX Listed','Egyptian','Sport / Lifestyle','—'),
('Ali F. Mostafa','@alimostafa','https://www.instagram.com/alimostafa/','P2','OKX Listed','Emirati','Film / Creative','—'),
('Dima Al Sharif','@dimasharifonline','https://www.instagram.com/dimasharifonline/','P2','OKX Listed','Palestinian','Food / Middle Eastern','—'),
('Zozo Kahramana','@zozokahramana','https://www.instagram.com/zozokahramana/','P2','OKX Listed','UAE','Humor / Lifestyle','—'),
('Daan de Rover (CryptoRover)','@cryptorover','https://www.instagram.com/cryptorover/','P2','Our Pick','Dutch-UAE','Crypto / Finance','52.5K'),
('Lilly Douse','@lillydouse','https://www.instagram.com/lillydouse/','P2','Our Pick','UAE','Lifestyle / Crypto','45.9K'),
('Rama Murad','@raamamurad','https://www.instagram.com/raamamurad/','P2','OKX Listed','—','Lifestyle / Fashion','—'),
('Farah Abdulhamed','@farahabdulhamed','https://www.instagram.com/farahabdulhamed/','P2','OKX Listed','Jordanian','Beauty / Lifestyle','—'),
('Maria Frackowiak','@merys_way','https://www.instagram.com/merys_way/','P2','Our Pick','European-UAE','Lifestyle / Micro','8.5K'),

-- === WAVE P3: COMMUNITY ===
('Aziza Faryal (CryptoGirlUAE)','@cryptogirluae','https://www.instagram.com/cryptogirluae/','P3','Our Pick','UAE','Crypto / Female','—'),
('Zahra Abdalla','@cookingwithzahra','https://www.instagram.com/cookingwithzahra/','P3','OKX Listed','Iran-Sudan','Food / Cookbook','—'),
('Lisa Helly Obrien','@MyLittleLovesBlog','https://www.instagram.com/MyLittleLovesBlog/','P3','OKX Listed','—','Family / Parenting','—'),
('Alex Augusti (JustFoodDXB)','@justfooddxb','https://www.instagram.com/justfooddxb/','P3','OKX Listed','UAE','Food / Casual Dining','—'),
('Lavina Israni','@lavinaisranicom','https://www.instagram.com/lavinaisranicom/','P3','OKX Listed','UAE','Food / Lifestyle','—'),
('Karen Mcclean (Secret Squirrel)','@secretsquirrelfood','https://www.instagram.com/secretsquirrelfood/','P3','OKX Listed','Australian-UAE','Food Blog','—'),
('Mona Essawi','@cookingis.art','https://www.instagram.com/cookingis.art/','P3','OKX Listed','UAE-Egypt','Healthy Lifestyle','—'),
('Nahla Ibrahim','@nahlaaibrahiim','https://www.instagram.com/nahlaaibrahiim/','P3','OKX Listed','Saudi-Egypt','Lifestyle','—'),
('Virdah Javed Khan','@mom_in_dubai','https://www.instagram.com/mom_in_dubai/','P3','OKX Listed','Pakistan-UAE','Mom / Lifestyle','—'),
('Aaisha','@dubai_blogger__','https://www.instagram.com/dubai_blogger__/','P3','OKX Listed','India-UAE','Food / Fashion','—'),
('Rafeez Ahmed','@tableeforone','https://www.instagram.com/tableeforone/','P3','OKX Listed','India-UAE','Food Blog','—'),
('Safia Mansoor','@cuptaleswithsafia','https://www.instagram.com/cuptaleswithsafia/','P3','OKX Listed','India-UAE','Food / Travel','—'),
('Ayshafarhana Tharammal','@ayeshas_kitche_n','https://www.instagram.com/ayeshas_kitche_n/','P3','OKX Listed','India-UAE','Lifestyle / YouTube','—'),
('Olena','@health_and_beauty_uae','https://www.instagram.com/health_and_beauty_uae/','P3','OKX Listed','UAE','Food / Wellness','—'),
('Sultan Kayed','@sultan.eats','https://www.instagram.com/sultan.eats/','P3','OKX Listed','UAE','Chef / Food','—'),
('Pooja Varyani','@foodishvibes','https://www.instagram.com/foodishvibes/','P3','OKX Listed','India-UAE','Vegetarian Food','—'),
('Anushree Bagzai','@anushreebagzai','https://www.instagram.com/anushreebagzai/','P3','OKX Listed','India-UAE','Travel / Food','—'),
('Arpita Soni','@foodloreuae','https://www.instagram.com/foodloreuae/','P3','OKX Listed','India-UAE','Food Blog','—'),
('Jedax Foodtrip','@jedax.foodtrip','https://www.instagram.com/jedax.foodtrip/','P3','OKX Listed','Philippines-UAE','Food / Travel','—'),
('Syed Muhammad Shabi','@shaybishah','https://www.instagram.com/shaybishah/','P3','OKX Listed','Pakistan-UAE','Food Blog','—'),
('Aemen Aisha','@adventuresofaemen','https://www.instagram.com/adventuresofaemen/','P3','OKX Listed','Pakistan-UAE','Lifestyle','—'),
('Danah Alshayji','@danaindxb','https://www.instagram.com/danaindxb/','P3','OKX Listed','Kuwaiti-UAE','Mom / Lifestyle','—'),
('Hupert Sepidnam (Mr. Taster)','@mr.taster','https://www.instagram.com/mr.taster/','P3','OKX Listed','UK-UAE','Food Blog','—'),
('Nawar H','@nawar.h6','https://www.instagram.com/nawar.h6/','P3','OKX Listed','—','Lifestyle / Fashion','—'),
('Firas Nour','@firas.nour','https://www.instagram.com/firas.nour/','P3','OKX Listed','—','Travel / Adventure','—'),
('Nouran M. Fawzy','@nmfeats','https://www.instagram.com/nmfeats/','P3','OKX Listed','—','Food / Lifestyle','—'),
('Lovin Dubai','@lovindubai','https://www.instagram.com/lovindubai/','P3','OKX Listed','UAE','Media / Lifestyle','—'),
('GRIT+TONIC','@gritandtonic','https://www.instagram.com/gritandtonic/','P3','OKX Listed','UAE','Fitness / Wellness','—'),
('Rooted Regimen','@rootedregimen','https://www.instagram.com/rootedregimen/','P3','OKX Listed','UAE','Wellness Brand','—'),
('OutQore','@outqore','https://www.instagram.com/outqore/','P3','OKX Listed','UAE','Activities / Community','—'),
('Al Oula Radio','@aloulafm','https://www.instagram.com/aloulafm/','P3','OKX Listed','Emirati','Radio / Media','34.2K'),
('UAE Barq','@uae_barq','https://www.instagram.com/uae_barq/','P3','OKX Listed','Emirati','Arabic News','—'),
('TFG 7 Emirates Cycle Challenge','@tfg7ecc','https://www.instagram.com/tfg7ecc/','P3','OKX Listed','UAE','Cycling / Community','—'),
('The National News','@thenationalnews','https://www.instagram.com/thenationalnews.com/','P3','OKX Approved','UAE','English Media','—'),
('DU Telecom','@Du','https://www.instagram.com/Du/','P3','OKX Listed','UAE','Telecom Brand','—'),
('Etisalat (e&)','@etisalat','https://www.instagram.com/etisalat/','P3','OKX Listed','UAE','Telecom Brand','—'),
('Natuzzi Italia Dubai','@natuzzi.uae','https://www.instagram.com/natuzzi.uae/','P3','OKX Listed','Italian-UAE','Furniture Brand','24.7K');
